Added support to strip out hex codes updated
Signed-off-by: PAnanyai <Ananya.P@ibm.com>

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -33,7 +33,7 @@ jobs:
         project:
           - { 
               name: tobi-example,
-              branch: hexenc_example,
+              branch: integration-test,
               lib: lib1,
               directory: functionsVAT,
               file: vat300.rpgle,
@@ -93,25 +93,6 @@ jobs:
             --cmd "touch ${{ matrix.project.directory }}/${{ matrix.project.file }}" \
             --cmd "../ibmi_tobi/bin/makei c -f ${{ matrix.project.directory }} -e ${{ matrix.project.lib }}=$(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}) | tee secondCompile.log" \
             --cmd "grep '${{ matrix.project.secondCompile }}' secondCompile.log || { echo 'Second compile of ${{ matrix.project.secondCompile }} failed!'; exit 1; }" \
-            --cmd "echo Testing cvtsrcpf with hex codes..." \
-            --rcwd "../${{ matrix.project.name }}" \
-            --ignore --cl "CRTSRCPF FILE($(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})/CCSID5026) CCSID(5026) RCDLEN(112)" \
-            --ignore --cl "CRTSRCPF FILE($(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})/CCSID5035) CCSID(5035) RCDLEN(112)" \
-            --ignore --cl "CRTSRCPF FILE($(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})/ALLHEXCODE) CCSID(37) RCDLEN(112)" \
-            --cl "CPYFRMSTMF FROMSTMF('./builds/github_ci/${GITHUB_SHA}/${{ matrix.project.name }}/HEXENC/TEST26.rpgle') TOMBR('/QSYS.LIB/$(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}).LIB/CCSID5026.FILE/TEST26CPY.MBR') STMFCCSID(5026) MBROPT(*REPLACE)" \
-            --cl "CPYFRMSTMF FROMSTMF('./builds/github_ci/${GITHUB_SHA}/${{ matrix.project.name }}/HEXENC/TEST35.rpgle') TOMBR('/QSYS.LIB/$(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}).LIB/CCSID5035.FILE/TEST35CPY.MBR') STMFCCSID(5035) MBROPT(*REPLACE)" \
-            --cl "CPYFRMSTMF FROMSTMF('./builds/github_ci/${GITHUB_SHA}/${{ matrix.project.name }}/HEXENC/ALLHEXCODE.rpgle') TOMBR('/QSYS.LIB/$(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}).LIB/ALLHEXCODE.FILE/ALLHXCPY.MBR') STMFCCSID(37) MBROPT(*REPLACE)" \
-            --cmd "../ibmi_tobi/bin/makei cvtsrcpf --srcfile ALLHXCPY --lib $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}) --output . --tolower | tee cvtsrcpf_allhex.log" \
-            --cmd "test -f ./.ibmi.json && echo 'ALLHEXCODE conversion successful' || { echo 'ALLHEXCODE conversion failed'; exit 1; }" \
-            --cmd "rm -f ./.ibmi.json allhxcpy.rpgle" \
-            --cmd "../ibmi_tobi/bin/makei cvtsrcpf --srcfile TEST26CPY --lib $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}) --output . --tolower | tee cvtsrcpf_5026.log" \
-            --cmd "test -f ./.ibmi.json && echo 'CCSID5026 conversion successful' || { echo 'CCSID5026 conversion failed'; exit 1; }" \
-            --cmd "rm -f ./.ibmi.json test26cpy.rpgle" \
-            --cmd "../ibmi_tobi/bin/makei cvtsrcpf --srcfile TEST35CPY --lib $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}) --output . --tolower | tee cvtsrcpf_5035.log" \
-            --cmd "test -f ./.ibmi.json && echo 'CCSID5035 conversion successful' || { echo 'CCSID5035 conversion failed'; exit 1; }" \
-            --cmd "rm -f ./.ibmi.json test35cpy.rpgle" \
-            --cmd "echo cvtsrcpf tests completed successfully" \
-            --rcwd "../${{ matrix.project.name }}" \
             --cmd "echo Clean up..." \
             --ignore --cl "DLTLIB $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})" \
             --rcwd "../../../github_ci/" \
@@ -203,5 +184,67 @@ jobs:
         env:
           IBMI_HOST: ${{ secrets.IBMI_HOST }}
           IBMI_USER: ${{ secrets.IASP_USER }}
+          IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
+          IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}
+
+  cvtsrcpf-test:
+    name: cvtsrcpf Test ${{ matrix.project.name }}
+    runs-on: ubuntu-latest
+    environment: COMMON1
+    strategy:
+      matrix:
+        project:
+          - {
+              name: tobi-example,
+              branch: hexenc_example
+            }
+    steps:
+      - name: Checkout ibmi-tobi
+        uses: actions/checkout@v4
+      - name: Set up Node.js 20.x
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20.x
+      - name: Install Dependencies
+        run: |
+          npm i -g @ibm/ibmi-ci
+          npm i -g @ibm/sourceorbit
+      - name: Run cvtsrcpf Tests on IBM i
+        run: |
+          ici \
+            --cmd "echo Setting up tobi..." \
+            --cmd "mkdir -p './builds/github_ci/${GITHUB_SHA}/ibmi_tobi'" \
+            --rcwd "./builds/github_ci/${GITHUB_SHA}/ibmi_tobi" \
+            --push "." \
+            --cmd "echo Setting up ${{ matrix.project.name }}..." \
+            --ignore --cl "CRTLIB $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})" \
+            --ignore --cl "CLRLIB $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})" \
+            --cmd "rm -rf ../${{ matrix.project.name }}" \
+            --cmd "git clone https://github.com/IBM/${{ matrix.project.name }}.git ../${{ matrix.project.name }}" \
+            --rcwd "../${{ matrix.project.name }}" \
+            --cmd "git switch ${{ matrix.project.branch }}" \
+            --cmd "echo Testing cvtsrcpf with hex codes..." \
+            --ignore --cl "CRTSRCPF FILE($(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})/CCSID5026) CCSID(5026) RCDLEN(112)" \
+            --ignore --cl "CRTSRCPF FILE($(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})/CCSID5035) CCSID(5035) RCDLEN(112)" \
+            --ignore --cl "CRTSRCPF FILE($(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})/ALLHEXCODE) CCSID(37) RCDLEN(112)" \
+            --cl "CPYFRMSTMF FROMSTMF('./builds/github_ci/${GITHUB_SHA}/${{ matrix.project.name }}/HEXENC/TEST26.rpgle') TOMBR('/QSYS.LIB/$(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}).LIB/CCSID5026.FILE/TEST26CPY.MBR') STMFCCSID(5026) MBROPT(*REPLACE)" \
+            --cl "CPYFRMSTMF FROMSTMF('./builds/github_ci/${GITHUB_SHA}/${{ matrix.project.name }}/HEXENC/TEST35.rpgle') TOMBR('/QSYS.LIB/$(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}).LIB/CCSID5035.FILE/TEST35CPY.MBR') STMFCCSID(5035) MBROPT(*REPLACE)" \
+            --cl "CPYFRMSTMF FROMSTMF('./builds/github_ci/${GITHUB_SHA}/${{ matrix.project.name }}/HEXENC/ALLHEXCODE.rpgle') TOMBR('/QSYS.LIB/$(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}).LIB/ALLHEXCODE.FILE/ALLHXCPY.MBR') STMFCCSID(37) MBROPT(*REPLACE)" \
+            --cmd "../ibmi_tobi/bin/makei cvtsrcpf --srcfile ALLHXCPY --lib $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}) --output . --tolower | tee cvtsrcpf_allhex.log" \
+            --cmd "test -f ./.ibmi.json && echo 'ALLHEXCODE conversion successful' || { echo 'ALLHEXCODE conversion failed'; exit 1; }" \
+            --cmd "rm -f ./.ibmi.json allhxcpy.rpgle" \
+            --cmd "../ibmi_tobi/bin/makei cvtsrcpf --srcfile TEST26CPY --lib $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}) --output . --tolower | tee cvtsrcpf_5026.log" \
+            --cmd "test -f ./.ibmi.json && echo 'CCSID5026 conversion successful' || { echo 'CCSID5026 conversion failed'; exit 1; }" \
+            --cmd "rm -f ./.ibmi.json test26cpy.rpgle" \
+            --cmd "../ibmi_tobi/bin/makei cvtsrcpf --srcfile TEST35CPY --lib $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }}) --output . --tolower | tee cvtsrcpf_5035.log" \
+            --cmd "test -f ./.ibmi.json && echo 'CCSID5035 conversion successful' || { echo 'CCSID5035 conversion failed'; exit 1; }" \
+            --cmd "rm -f ./.ibmi.json test35cpy.rpgle" \
+            --cmd "echo cvtsrcpf tests completed successfully" \
+            --cmd "echo Clean up..." \
+            --ignore --cl "DLTLIB $(so -bl ${GITHUB_HEAD_REF}_${{ matrix.project.name }})" \
+            --rcwd "../../../github_ci/" \
+        env:
+          IBMI_HOST: ${{ secrets.IBMI_HOST }}
+          IBMI_USER: ${{ secrets.IBMI_USER }}
           IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
           IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}
